#!/usr/bin/env node
"use strict";
// sticky-utils.js — Shared utilities for Sticky Note hooks.
// Copied into .sticky-note/hooks/ during `npx sticky-note init` and required by all hook scripts.
// Exports helpers for path resolution, JSON I/O, git operations, thread management, audit logging, and pattern matching.
// Do not edit this file directly in .sticky-note/hooks/ — edit the template at templates/hooks/sticky-utils.js instead.

const fs = require("fs");
const path = require("path");
const { execFileSync } = require("child_process");

// ── Cross-platform path normalization ──────────────────────

// Normalize path separators to forward slashes for consistent storage/comparison.
function normalizeSep(p) {
  return typeof p === "string" ? p.replace(/\\/g, "/") : p;
}

// ── Shared regex patterns ─────────────────────────────────

const ERROR_PATTERNS = new RegExp(
  "(error|exception|traceback|failed|fatal|panic|ENOENT|EACCES|" +
    "segfault|undefined|TypeError|SyntaxError|ReferenceError|" +
    "ImportError|ModuleNotFoundError|KeyError|ValueError|" +
    "RuntimeError|ConnectionError|TimeoutError|PermissionError)",
  "i"
);

const RETRY_PATTERNS = new RegExp(
  "(try again|let me try|didn't work|doesn't work|failed|let's try|" +
    "another approach|instead|alternatively|that approach|this doesn't|" +
    "that didn't|won't work|can't|cannot)",
  "i"
);

const FILE_PATH_PATTERN = /[\w./\\-]+\.\w{1,10}/g;

// ── Path helpers ──────────────────────────────────────────

function _stickyDir() {
  try {
    const gitDir = execFileSync("git", ["rev-parse", "--absolute-git-dir"], {
      encoding: "utf-8", timeout: 3000, stdio: ["pipe", "pipe", "pipe"],
    }).trim();
    return path.resolve(gitDir, "sticky-note");
  } catch (_) {
    // Fallback for non-git environments (e.g., unit tests without git init)
    const scriptDir = path.dirname(path.resolve(__filename));
    return path.join(scriptDir, "..", "..", ".sticky-note");
  }
}

// ── Error logging ─────────────────────────────────────────

function logHookError(hookName, error) {
  try {
    const logPath = path.join(_stickyDir(), ".sticky-errors.log");
    const ts = new Date().toISOString();
    const msg = error instanceof Error ? error.stack || error.message : String(error);
    const line = `[${ts}] ${hookName}: ${msg}\n`;
    fs.mkdirSync(path.dirname(logPath), { recursive: true });
    fs.appendFileSync(logPath, line, "utf-8");
  } catch (_) {
    // Last resort — can't even log the error
  }
}

// Issue #14: Surface hook failures to stderr so the host tool's generic
// "<HookName> hook error" message has actionable detail next to it. Earlier
// versions silently swallowed `require()` failures and top-level exceptions,
// which made stale-path issues (#13) and other crashes impossible to diagnose
// — particularly under UserPromptSubmit, which Claude Code reports without
// a stack trace. This helper prefixes every line with `[STICKY-NOTE]` so the
// user can spot it in mixed hook output.
function reportHookError(hookName, error, hint) {
  const msg = error instanceof Error ? (error.stack || error.message) : String(error);
  const lines = [`[STICKY-NOTE] ${hookName} hook error: ${msg}`];
  if (hint) lines.push(`[STICKY-NOTE]   hint: ${hint}`);
  try { process.stderr.write(lines.join("\n") + "\n"); } catch (_) { /* ignore */ }
  try { logHookError(hookName, error); } catch (_) { /* ignore */ }
}

// Issue #13: When a teammate copies `.claude/settings.json` from another
// machine (or runs an older sticky-note-cli that wrote absolute paths), the
// hook commands point at non-existent absolute paths and every hook fails
// with MODULE_NOT_FOUND. Re-running `npx sticky-note init` fixes it, but
// users typically don't know that — they just see "<Hook> hook error" each
// session. This helper detects and rewrites those stale commands in-place
// the first time any hook (e.g. session-start, inject-context) successfully
// loads, so the next session starts clean.
//
// The rewritten command uses `npx sticky-note run-hook <basename>` which walks
// up the directory tree to find `.claude/hooks/<basename>.js`, so it works even
// when Claude Code is launched from a subdirectory of the project root.
// We extract `<basename>` from the existing command so we never invent hook
// scripts that don't exist.
//
// Returns the list of (hookEvent, oldCommand, newCommand) tuples that were
// rewritten, or [] if nothing was stale.
function selfHealHookPaths(settingsPath) {
  const result = [];
  try {
    if (!settingsPath) {
      settingsPath = path.join(process.cwd(), ".claude", "settings.json");
    }
    if (!fs.existsSync(settingsPath)) return result;

    const raw = fs.readFileSync(settingsPath, "utf-8");
    let settings;
    try { settings = JSON.parse(raw); } catch (_) { return result; }
    if (!settings || !settings.hooks) return result;

    // Two stale patterns:
    // 1. Absolute paths (written by older sticky-note-cli or copied from another machine)
    // 2. Old relative form `node ".claude/hooks/foo.js"` — fails when Claude Code
    //    launches from a subdirectory, because the path resolves relative to the
    //    launch cwd, not the directory containing .claude/settings.json.
    const STALE_ABSOLUTE = /["'][A-Za-z]:[\\/]|["']\/(?:Users|home|root|tmp)\/|\$\(git rev-parse/;
    const STALE_RELATIVE = /^node\s+["']\.claude[\\/]hooks[\\/][^"']+\.js["']\s*$/;
    // Match the script basename in either quoted or bare form.
    const BASENAME = /([A-Za-z0-9_.-]+)\.(?:js|sh|cjs|mjs)(?:["'`\s]|$)/;

    let changed = false;
    for (const [event, entries] of Object.entries(settings.hooks)) {
      if (!Array.isArray(entries)) continue;
      for (const entry of entries) {
        for (const h of (entry && entry.hooks) || []) {
          const cmd = h && h.command;
          if (typeof cmd !== "string") continue;
          const isStale = STALE_ABSOLUTE.test(cmd) || STALE_RELATIVE.test(cmd);
          if (!isStale) continue;
          const m = cmd.match(BASENAME);
          if (!m) continue;
          const basename = m[1];
          const newCmd = `npx sticky-note run-hook ${basename}`;
          result.push({ event, oldCommand: cmd, newCommand: newCmd });
          h.command = newCmd;
          changed = true;
        }
      }
    }

    if (!changed) return result;

    fs.writeFileSync(settingsPath, JSON.stringify(settings, null, 2) + "\n", "utf-8");
    try {
      const summary =
        `[STICKY-NOTE] ⚠️  Detected ${result.length} stale hook path(s) in ` +
        `${path.relative(process.cwd(), settingsPath) || settingsPath} — rewrote to ` +
        `"npx sticky-note run-hook <name>" so hooks work from any subdirectory. ` +
        `Commit the change to share the fix with your team.`;
      process.stderr.write(summary + "\n");
      for (const { event, oldCommand, newCommand } of result.slice(0, 5)) {
        process.stderr.write(`[STICKY-NOTE]   ${event}: ${oldCommand} → ${newCommand}\n`);
      }
    } catch (_) { /* non-fatal */ }
  } catch (err) {
    try { logHookError("selfHealHookPaths", err); } catch (_) { /* ignore */ }
  }
  return result;
}

const _paths = {
  memory: "sticky-note.json",
  config: "sticky-note-config.json",
  auditDir: "audit",
  presenceDir: "presence",
  // Legacy single-file paths (for migration only)
  legacyAudit: "sticky-note-audit.jsonl",
  legacyPresence: ".sticky-presence.json",
  resume: ".sticky-resume",
  session: ".sticky-session",
  head: ".sticky-head",
};
const _p = (key) => path.join(_stickyDir(), _paths[key]);

function getMemoryPath() { return _p("memory"); }
function getConfigPath() { return _p("config"); }
function getAuditDir() { return _p("auditDir"); }
function getPresenceDir() { return _p("presenceDir"); }
function getLegacyAuditPath() { return _p("legacyAudit"); }
function getLegacyPresencePath() { return _p("legacyPresence"); }

function getUserAuditPath(user) {
  if (!user) user = getUser();
  return path.join(getAuditDir(), user + ".jsonl");
}

function getUserPresencePath(user) {
  if (!user) user = getUser();
  return path.join(getPresenceDir(), user + ".json");
}

function getAllAuditPaths() {
  const dir = getAuditDir();
  try {
    return fs.readdirSync(dir)
      .filter((f) => f.endsWith(".jsonl"))
      .map((f) => path.join(dir, f));
  } catch (_) {
    return [];
  }
}

function getAllPresencePaths() {
  const dir = getPresenceDir();
  try {
    return fs.readdirSync(dir)
      .filter((f) => f.endsWith(".json"))
      .map((f) => path.join(dir, f));
  } catch (_) {
    return [];
  }
}

// Backwards-compatible aliases (read from all per-user files)
function getAuditPath() { return getUserAuditPath(); }
function getPresencePath() { return getUserPresencePath(); }
function getResumePath() { return _p("resume"); }
function getSessionFilePath() { return _p("session"); }
function getHeadFilePath() { return _p("head"); }

function saveSessionId(sessionId) {
  const filePath = getSessionFilePath();
  fs.mkdirSync(path.dirname(filePath), { recursive: true });
  fs.writeFileSync(filePath, sessionId + "\n", "utf-8");
}

function readSessionIdFromFile() {
  try {
    const sid = fs.readFileSync(getSessionFilePath(), "utf-8").trim();
    return sid || null;
  } catch (_) {
    return null;
  }
}

function clearSessionFile() {
  try {
    fs.unlinkSync(getSessionFilePath());
  } catch (_) {
    // ignore
  }
}

// ── Git sync (auto-commit/push .sticky-note/ files) ──────

function _gitRepoRoot() {
  try {
    return execFileSync("git", ["rev-parse", "--show-toplevel"], {
      encoding: "utf-8", timeout: 5000, stdio: ["pipe", "pipe", "pipe"],
    }).trim();
  } catch (_) {
    return null;
  }
}

/**
 * Stage, commit, and optionally push .sticky-note/ files.
 * Returns { committed: bool, pushed: bool, skipped: bool, error?: string }
 */
function syncStickyNote(opts) {
  const push = opts && opts.push;
  const result = { committed: false, pushed: false, skipped: false };
  try {
    const root = _gitRepoRoot();
    if (!root) { result.skipped = true; return result; }

    const syncGuard = path.join(_stickyDir(), ".sticky-syncing");
    if (fs.existsSync(syncGuard)) { result.skipped = true; return result; }

    // Check for dirty .sticky-note/ files (staged or unstaged)
    const status = execFileSync("git", [
      "status", "--porcelain", "--", ".sticky-note/sticky-note.json",
      ".sticky-note/audit/", ".sticky-note/presence/"
    ], { encoding: "utf-8", timeout: 5000, stdio: ["pipe", "pipe", "pipe"] }).trim();

    if (!status) { result.skipped = true; return result; }

    // Write guard to prevent recursive post-commit triggers
    fs.writeFileSync(syncGuard, process.pid.toString(), "utf-8");

    try {
      // Stage the relevant files
      execFileSync("git", [
        "add", "--", ".sticky-note/sticky-note.json",
        ".sticky-note/audit/", ".sticky-note/presence/"
      ], { timeout: 10000, stdio: ["pipe", "pipe", "pipe"] });

      // Commit only what was staged
      execFileSync("git", [
        "commit", "-m", "chore(sticky-note): sync thread data", "--no-verify"
      ], { timeout: 15000, stdio: ["pipe", "pipe", "pipe"] });
      result.committed = true;

      // Push if requested
      if (push) {
        execFileSync("git", ["push"], {
          timeout: 30000, stdio: ["pipe", "pipe", "pipe"],
        });
        result.pushed = true;
      }
    } finally {
      try { fs.unlinkSync(syncGuard); } catch (_) {}
    }
  } catch (err) {
    result.error = err.message;
    logHookError("syncStickyNote", err);
  }
  return result;
}

// ── Git HEAD snapshot (for files_touched fallback) ────────

function saveHeadSha() {
  try {
    const sha = execFileSync("git", ["rev-parse", "HEAD"], {
      encoding: "utf-8",
      timeout: 5000,
      stdio: ["pipe", "pipe", "pipe"],
    }).trim();
    if (sha) {
      const filePath = getHeadFilePath();
      fs.mkdirSync(path.dirname(filePath), { recursive: true });
      fs.writeFileSync(filePath, sha + "\n", "utf-8");
    }
  } catch (_) {
    // ignore
  }
}

function readHeadSha() {
  try {
    const sha = fs.readFileSync(getHeadFilePath(), "utf-8").trim();
    return sha || null;
  } catch (_) {
    return null;
  }
}

function clearHeadFile() {
  try {
    fs.unlinkSync(getHeadFilePath());
  } catch (_) {
    // ignore
  }
}

// ── Thread resume helpers ─────────────────────────────────

function getResumeThreadId() {
  try {
    const threadId = fs.readFileSync(getResumePath(), "utf-8").trim();
    return threadId || null;
  } catch (_) {
    return null;
  }
}

function findThreadById(threads, threadId) {
  for (const thread of threads) {
    if (thread.id === threadId) {
      return thread;
    }
  }
  return null;
}

function clearResumeSignal() {
  try {
    fs.unlinkSync(getResumePath());
  } catch (_) {
    // ignore
  }
}

// ── JSON I/O ─────────────────────────────────────────────

function loadJson(filePath, defaultVal) {
  try {
    const raw = fs.readFileSync(filePath, "utf-8");
    return JSON.parse(raw);
  } catch (_) {
    return defaultVal !== undefined ? defaultVal : {};
  }
}

function saveJson(filePath, data) {
  fs.mkdirSync(path.dirname(filePath), { recursive: true });
  // Atomic write: write to temp file then rename to prevent partial/truncated JSON
  const tmpPath = filePath + ".tmp." + process.pid;
  try {
    fs.writeFileSync(tmpPath, JSON.stringify(data, null, 2) + "\n", "utf-8");
    fs.renameSync(tmpPath, filePath);
  } catch (err) {
    // Rename can fail on some Windows configs; fall back to direct write
    try { fs.unlinkSync(tmpPath); } catch (_) {}
    fs.writeFileSync(filePath, JSON.stringify(data, null, 2) + "\n", "utf-8");
  }
}

// ── File locking ─────────────────────────────────────────

const LOCK_STALE_MS = 10000; // 10 seconds
const LOCK_RETRY_MS = 50;
const LOCK_MAX_RETRIES = 60; // 3 seconds max wait

function acquireLock(memoryPath) {
  const lockPath = memoryPath + ".lock";
  for (let i = 0; i < LOCK_MAX_RETRIES; i++) {
    try {
      // Exclusive create — fails if lock already exists
      fs.writeFileSync(lockPath, JSON.stringify({ pid: process.pid, ts: Date.now() }), { flag: "wx" });
      return lockPath;
    } catch (_) {
      // Lock exists — check if stale
      try {
        const lock = JSON.parse(fs.readFileSync(lockPath, "utf-8"));
        if (Date.now() - lock.ts > LOCK_STALE_MS) {
          // Stale lock — remove and retry
          try { fs.unlinkSync(lockPath); } catch (_) {}
          continue;
        }
      } catch (_) {
        // Can't read lock — remove and retry
        try { fs.unlinkSync(lockPath); } catch (_) {}
        continue;
      }
      // Lock is fresh — wait and retry
      const waitUntil = Date.now() + LOCK_RETRY_MS;
      while (Date.now() < waitUntil) { /* busy wait */ }
    }
  }
  // Couldn't acquire after retries — proceed without lock (best effort)
  return null;
}

function releaseLock(lockPath) {
  if (!lockPath) return;
  try { fs.unlinkSync(lockPath); } catch (_) {}
}

// ── Backup rotation ──────────────────────────────────────

const MAX_BACKUPS = 3;

function rotateBackup(memoryPath) {
  const dir = path.dirname(memoryPath);
  const backupDir = path.join(dir, ".sticky-backups");
  try {
    fs.mkdirSync(backupDir, { recursive: true });
    // Read current file
    const current = fs.readFileSync(memoryPath, "utf-8");
    // Rotate: remove oldest, shift names
    for (let i = MAX_BACKUPS; i > 1; i--) {
      const older = path.join(backupDir, `sticky-note.${i - 1}.json`);
      const newer = path.join(backupDir, `sticky-note.${i}.json`);
      try {
        if (fs.existsSync(older)) fs.renameSync(older, newer);
      } catch (_) {}
    }
    // Write newest backup
    fs.writeFileSync(path.join(backupDir, "sticky-note.1.json"), current, "utf-8");
  } catch (_) {
    // Backup failure is non-fatal
  }
}

function loadLatestBackup(memoryPath) {
  const backupDir = path.join(path.dirname(memoryPath), ".sticky-backups");
  for (let i = 1; i <= MAX_BACKUPS; i++) {
    try {
      const bp = path.join(backupDir, `sticky-note.${i}.json`);
      return JSON.parse(fs.readFileSync(bp, "utf-8"));
    } catch (_) {
      continue;
    }
  }
  return null;
}

/**
 * Detect threads lost since last backup (e.g., after git reset/rollback).
 * Returns array of thread IDs that are in backup but not in current.
 */
function detectLostThreads(memoryPath) {
  try {
    const current = loadJson(memoryPath, { threads: [] });
    const backup = loadLatestBackup(memoryPath);
    if (!backup || !Array.isArray(backup.threads)) return [];
    const currentIds = new Set(
      (current.threads || []).filter(Boolean).map((t) => t.id)
    );
    return (backup.threads || []).filter(
      (t) => t && t.id && !currentIds.has(t.id) && t.status !== "expired"
    );
  } catch (_) {
    return [];
  }
}

/**
 * Merge-on-write for the memory file. Re-reads the file from disk before
 * writing and preserves any threads (by ID) that exist on disk but not in
 * the in-memory copy. For same-ID threads, performs field-level 2-way merge
 * to prevent concurrent sessions from clobbering each other's changes.
 *
 * Uses file locking, atomic writes, and rolling backups.
 */
function saveMemoryMerged(memoryPath, memory) {
  const lockPath = acquireLock(memoryPath);
  try {
    // Create backup before writing
    if (fs.existsSync(memoryPath)) {
      rotateBackup(memoryPath);
    }

    // Load merge helpers (field-level thread merge)
    let mergeOneThread2Way = null;
    try {
      const md = require(path.join(path.dirname(memoryPath), "merge-driver.js"));
      mergeOneThread2Way = md.mergeOneThread2Way;
    } catch (_) {}

    try {
      const onDisk = loadJson(memoryPath, { threads: [] });
      const onDiskThreads = Array.isArray(onDisk.threads) ? onDisk.threads.filter(Boolean) : [];
      const inMemoryThreads = Array.isArray(memory.threads) ? memory.threads.filter(Boolean) : [];
      const inMemoryMap = new Map(inMemoryThreads.map((t) => [t.id, t]));

      for (const diskThread of onDiskThreads) {
        if (!diskThread.id) continue;
        if (!inMemoryMap.has(diskThread.id)) {
          // Thread only on disk — preserve it
          memory.threads.push(diskThread);
        } else if (mergeOneThread2Way) {
          // Thread on both — field-level merge
          const inMemThread = inMemoryMap.get(diskThread.id);
          const merged = mergeOneThread2Way(inMemThread, diskThread);
          // Replace in-memory version with merged version
          const idx = memory.threads.findIndex((t) => t && t.id === diskThread.id);
          if (idx >= 0) memory.threads[idx] = merged;
        }
      }
    } catch (_) {
      // If re-read/merge fails, proceed with what we have
    }

    saveJson(memoryPath, memory);
  } finally {
    releaseLock(lockPath);
  }
}

function appendAuditLine(entry) {
  const filePath = getUserAuditPath();
  fs.mkdirSync(path.dirname(filePath), { recursive: true });
  fs.appendFileSync(filePath, JSON.stringify(entry) + "\n", "utf-8");
}

// ── Environment helpers ───────────────────────────────────

function getUser() {
  return process.env.USER || process.env.USERNAME || "unknown";
}

function detectTool(hookInput) {
  if (process.argv.includes("--copilot-cli")) {
    return "copilot-cli";
  }
  if (process.env.COPILOT_CLI) {
    return "copilot-cli";
  }
  if (hookInput) {
    const event = hookInput.hook_event_name || "";
    if (event && event[0] === event[0].toUpperCase() && event[0] !== event[0].toLowerCase()) {
      return "claude-code";
    }
    if (event && event[0] === event[0].toLowerCase() && event[0] !== event[0].toUpperCase()) {
      return "copilot-cli";
    }
    if ("transcript_path" in hookInput) {
      return "claude-code";
    }
  }
  return "unknown";
}

function getSessionId(hookInput) {
  if (hookInput) {
    for (const key of ["session_id", "sessionId", "session"]) {
      const val = hookInput[key];
      if (val && val !== "unknown") {
        return val;
      }
    }
  }
  for (const envKey of ["SESSION_ID", "GITHUB_COPILOT_SESSION_ID", "WT_SESSION"]) {
    const val = process.env[envKey];
    if (val) {
      return val;
    }
  }
  const fileSid = readSessionIdFromFile();
  if (fileSid) {
    return fileSid;
  }
  return "unknown";
}

function getBranch() {
  try {
    const result = execFileSync("git", ["rev-parse", "--abbrev-ref", "HEAD"], {
      encoding: "utf-8",
      timeout: 5000,
      stdio: ["pipe", "pipe", "pipe"],
    }).trim();
    return result;
  } catch (_) {
    return "";
  }
}

// ── Transcript parsing helpers ────────────────────────────

function parseJsonlFile(filePath) {
  const entries = [];
  try {
    const raw = fs.readFileSync(filePath, "utf-8");
    for (const line of raw.split(/\r?\n/)) {
      const trimmed = line.trim();
      if (!trimmed) continue;
      try {
        entries.push(JSON.parse(trimmed));
      } catch (_) {
        continue;
      }
    }
  } catch (_) {
    // ignore
  }
  return entries;
}

function extractNarrativeFromEntries(entries) {
  const lastTexts = [];
  for (const entry of entries) {
    const message = entry.message;
    if (!message || typeof message !== "object" || Array.isArray(message)) {
      continue;
    }
    const role = message.role || entry.role || "";
    if (role !== "assistant") continue;
    const content = message.content || entry.content || [];
    if (Array.isArray(content)) {
      for (const block of content) {
        if (block && typeof block === "object" && block.type === "text") {
          const text = (block.text || "").trim();
          if (text) {
            lastTexts.push(text);
          }
        }
      }
    }
  }
  if (lastTexts.length === 0) return "";
  return lastTexts[lastTexts.length - 1].substring(0, 300).trim();
}

function extractNarrativeFromText(lines) {
  const textBlocks = [];
  let currentBlock = [];

  for (const line of lines) {
    const stripped = line.trim();
    if (stripped) {
      currentBlock.push(stripped);
    } else if (currentBlock.length) {
      textBlocks.push(currentBlock.join(" "));
      currentBlock = [];
    }
  }
  if (currentBlock.length) {
    textBlocks.push(currentBlock.join(" "));
  }

  if (textBlocks.length === 0) return "";

  for (let i = textBlocks.length - 1; i >= 0; i--) {
    if (textBlocks[i].length > 20) {
      return textBlocks[i].substring(0, 300).trim();
    }
  }
  return "";
}

function extractFailedFromEntries(entries) {
  const approaches = [];

  for (const entry of entries) {
    const message = entry.message;
    if (!message || typeof message !== "object" || Array.isArray(message)) {
      continue;
    }
    const content = message.content || entry.content || [];
    if (!Array.isArray(content)) continue;

    for (const block of content) {
      if (!block || typeof block !== "object" || block.type !== "text") {
        continue;
      }
      const text = block.text || "";
      if (RETRY_PATTERNS.test(text) && ERROR_PATTERNS.test(text)) {
        const errorMatch = ERROR_PATTERNS.exec(text);
        let errorCtx = "";
        if (errorMatch) {
          const start = Math.max(0, errorMatch.index - 40);
          errorCtx = text.substring(start, errorMatch.index + errorMatch[0].length + 60).trim();
        }
        // Reset lastIndex for the global regex before using it
        FILE_PATH_PATTERN.lastIndex = 0;
        const filesTried = [];
        let m;
        while ((m = FILE_PATH_PATTERN.exec(text)) !== null && filesTried.length < 5) {
          filesTried.push(m[0]);
        }
        approaches.push({
          description: text.substring(0, 150).trim(),
          error: errorCtx.substring(0, 100),
          files_tried: filesTried,
        });
      }
    }
  }

  return approaches.slice(0, 5);
}

function extractFailedFromText(lines) {
  const approaches = [];
  const fullText = lines.join("\n");
  const paragraphs = fullText.split("\n\n");

  for (const para of paragraphs) {
    if (RETRY_PATTERNS.test(para) && ERROR_PATTERNS.test(para)) {
      const errorMatch = ERROR_PATTERNS.exec(para);
      let errorCtx = "";
      if (errorMatch) {
        const start = Math.max(0, errorMatch.index - 40);
        errorCtx = para.substring(start, errorMatch.index + errorMatch[0].length + 60).trim();
      }
      FILE_PATH_PATTERN.lastIndex = 0;
      const filesTried = [];
      let m;
      while ((m = FILE_PATH_PATTERN.exec(para)) !== null && filesTried.length < 5) {
        filesTried.push(m[0]);
      }
      approaches.push({
        description: para.substring(0, 150).trim(),
        error: errorCtx.substring(0, 100),
        files_tried: filesTried,
      });
    }
  }

  return approaches.slice(0, 5);
}

// ── Audit trail extraction ────────────────────────────────

function extractSessionFromAudit(sessionId) {
  const result = { prompts: [], tools: {}, files: [], first_prompt: null };
  if (!sessionId || sessionId === "unknown") return result;

  const auditPaths = getAllAuditPaths();
  if (auditPaths.length === 0) return result;

  for (const auditPath of auditPaths) {
    try {
      const raw = fs.readFileSync(auditPath, "utf-8");
      for (const line of raw.split(/\r?\n/)) {
        const trimmed = line.trim();
        if (!trimmed) continue;
        let entry;
        try {
          entry = JSON.parse(trimmed);
        } catch (_) {
          continue;
        }
        if (entry.session_id !== sessionId) continue;

        const entryType = entry.type || "";
        if (entryType === "user_prompt") {
          const prompt = (entry.prompt || "").trim();
          if (prompt) {
            result.prompts.push(prompt);
            if (result.first_prompt === null) {
              result.first_prompt = prompt;
            }
          }
        } else if (entryType === "tool_use") {
          const toolName = entry.tool || "";
          if (toolName) {
            result.tools[toolName] = (result.tools[toolName] || 0) + 1;
          }
          const filePath = entry.file || "";
          if (filePath && !result.files.includes(filePath)) {
            result.files.push(filePath);
          }
        }
      }
    } catch (_) {
      // ignore individual file failures
    }
  }

  return result;
}

// ── Migration: single-file → per-user ─────────────────────

function migrateAuditAndPresence() {
  const user = getUser();

  // Migrate legacy audit file
  const legacyAudit = getLegacyAuditPath();
  try {
    if (fs.existsSync(legacyAudit)) {
      const dest = getUserAuditPath(user);
      fs.mkdirSync(path.dirname(dest), { recursive: true });
      if (fs.existsSync(dest)) {
        // Append legacy content to existing per-user file
        const content = fs.readFileSync(legacyAudit, "utf-8");
        fs.appendFileSync(dest, content);
      } else {
        fs.renameSync(legacyAudit, dest);
      }
      // Clean up if rename didn't delete it
      try { if (fs.existsSync(legacyAudit)) fs.unlinkSync(legacyAudit); } catch (_) {}
    }
  } catch (_) {
    // ignore migration failures
  }

  // Migrate legacy presence file
  const legacyPresence = getLegacyPresencePath();
  try {
    if (fs.existsSync(legacyPresence)) {
      const data = loadJson(legacyPresence, {});
      const presenceDir = getPresenceDir();
      fs.mkdirSync(presenceDir, { recursive: true });
      // Split presence data: each key is a username
      for (const [u, info] of Object.entries(data)) {
        const dest = getUserPresencePath(u);
        saveJson(dest, info);
      }
      fs.unlinkSync(legacyPresence);
    }
  } catch (_) {
    // ignore migration failures
  }
}

// ── Injected-this-session tracking (V2.5) ─────────────────

const _injectedPaths = {
  injected: ".sticky-injected",
};
const _injectedP = (key) => path.join(_stickyDir(), _injectedPaths[key]);

function getInjectedPath() { return _injectedP("injected"); }

function loadInjectedSet() {
  try {
    const data = loadJson(getInjectedPath(), { thread_ids: [], session_id: null });
    return data;
  } catch (_) {
    return { thread_ids: [], session_id: null };
  }
}

function saveInjectedSet(data) {
  saveJson(getInjectedPath(), data);
}

function clearInjectedSet() {
  try {
    fs.unlinkSync(getInjectedPath());
  } catch (_) {
    // ignore
  }
}

function isThreadInjected(threadId, sessionId) {
  const data = loadInjectedSet();
  // Only consider threads injected in the SAME session — the file is shared
  // across concurrent sessions and stale entries from other sessions must
  // not suppress injection.
  if (sessionId && data.session_id && data.session_id !== sessionId) {
    return false;
  }
  return (data.thread_ids || []).includes(threadId);
}

function markThreadInjected(threadId, sessionId) {
  const data = loadInjectedSet();
  data.session_id = sessionId || data.session_id;
  if (!(data.thread_ids || []).includes(threadId)) {
    data.thread_ids = data.thread_ids || [];
    data.thread_ids.push(threadId);
  }
  saveInjectedSet(data);
}

// ── Overlap warning tracking (V2.6.11) ────────────────────
// Uses COPILOT_LOADER_PID to identify each Copilot CLI session uniquely.
// Each session gets its own overlap-warned flag, preventing cross-session
// poisoning. The flag file stores a JSON object keyed by PID.

const _overlapFlagPath = () => path.join(_stickyDir(), ".overlap-warned");

function _getCopilotPid() {
  return process.env.COPILOT_LOADER_PID || null;
}

function isOverlapWarned() {
  const pid = _getCopilotPid();
  if (!pid) return false;
  try {
    const data = JSON.parse(fs.readFileSync(_overlapFlagPath(), "utf-8"));
    return !!data[pid];
  } catch (_) {
    return false;
  }
}

function markOverlapWarned() {
  const pid = _getCopilotPid();
  if (!pid) return;
  let data = {};
  try {
    data = JSON.parse(fs.readFileSync(_overlapFlagPath(), "utf-8"));
  } catch (_) { /* empty or missing */ }
  // Clean up stale PIDs (older than 1 hour)
  const now = Date.now();
  for (const [k, v] of Object.entries(data)) {
    if (now - v > 3600000) delete data[k];
  }
  data[pid] = now;
  try {
    fs.writeFileSync(_overlapFlagPath(), JSON.stringify(data), "utf-8");
  } catch (_) { /* ignore */ }
}

// Signal file helpers — kept for backward compat but no longer primary
const _overlapPendingPath = () => path.join(_stickyDir(), ".overlap-pending");
const _overlapDismissedPath = () => path.join(_stickyDir(), ".overlap-dismissed");
function writeOverlapSignal(text) { try { fs.writeFileSync(_overlapPendingPath(), text, "utf-8"); } catch (_) {} }
function readAndDeleteOverlapSignal() { try { const c = fs.readFileSync(_overlapPendingPath(), "utf-8"); fs.unlinkSync(_overlapPendingPath()); return c || null; } catch (_) { return null; } }
function isOverlapDismissed(ttlMs) { try { const e = Date.now() - new Date(fs.readFileSync(_overlapDismissedPath(), "utf-8").trim()).getTime(); return e < (ttlMs || 300000); } catch (_) { return false; } }
function markOverlapDismissed() { try { fs.writeFileSync(_overlapDismissedPath(), new Date().toISOString(), "utf-8"); } catch (_) {} }

// ── Active resumed thread tracking (V2.5) ─────────────────

const _activeResumePath = () => path.join(_stickyDir(), ".sticky-active-resume");

function getActiveResumeThreadId() {
  try {
    const raw = fs.readFileSync(_activeResumePath(), "utf-8").trim();
    return raw || null;
  } catch (_) {
    return null;
  }
}

function setActiveResumeThreadId(threadId) {
  const filePath = _activeResumePath();
  fs.mkdirSync(path.dirname(filePath), { recursive: true });
  fs.writeFileSync(filePath, threadId + "\n", "utf-8");
}

function clearActiveResumeThreadId() {
  try {
    fs.unlinkSync(_activeResumePath());
  } catch (_) {
    // ignore
  }
}

// ── Copilot CLI MCP config helpers ────────────────────────

function getCopilotCliConfigDir() {
  if (process.env.COPILOT_HOME) return process.env.COPILOT_HOME;
  const home = process.env.HOME || process.env.USERPROFILE;
  if (!home) return null;
  return path.join(home, ".copilot");
}

function getCopilotCliMcpConfigPath() {
  const dir = getCopilotCliConfigDir();
  return dir ? path.join(dir, "mcp-config.json") : null;
}

/**
 * Register an MCP server in Copilot CLI's ~/.copilot/mcp-config.json.
 * Only writes if the ~/.copilot/ directory already exists (Copilot CLI installed).
 * Returns true if written, false if skipped.
 */
function ensureMcpInCopilotCliConfig(serverName, serverConfig) {
  try {
    const configDir = getCopilotCliConfigDir();
    if (!configDir || !fs.existsSync(configDir)) return false;

    const configPath = path.join(configDir, "mcp-config.json");
    let config = {};
    if (fs.existsSync(configPath)) {
      try {
        config = JSON.parse(fs.readFileSync(configPath, "utf-8"));
      } catch (_) {
        config = {};
      }
    }

    config.mcpServers = config.mcpServers || {};
    const existing = config.mcpServers[serverName];
    // Copilot CLI requires "tools" field — fix entries missing it
    if (existing) {
      if (!existing.tools) {
        existing.tools = ["*"];
        fs.writeFileSync(configPath, JSON.stringify(config, null, 2) + "\n");
        return true;
      }
      return false; // already registered with tools
    }

    // Ensure tools field is present for Copilot CLI compatibility
    if (!serverConfig.tools) serverConfig.tools = ["*"];
    config.mcpServers[serverName] = serverConfig;
    fs.writeFileSync(configPath, JSON.stringify(config, null, 2) + "\n");
    return true;
  } catch (_) {
    return false;
  }
}

// ── Exports ───────────────────────────────────────────────

module.exports = {
  ERROR_PATTERNS,
  RETRY_PATTERNS,
  FILE_PATH_PATTERN,
  logHookError,
  reportHookError,
  selfHealHookPaths,
  getMemoryPath,
  getConfigPath,
  getAuditPath,
  getAuditDir,
  getUserAuditPath,
  getAllAuditPaths,
  getPresencePath,
  getPresenceDir,
  getUserPresencePath,
  getAllPresencePaths,
  getLegacyAuditPath,
  getLegacyPresencePath,
  getResumePath,
  getSessionFilePath,
  saveSessionId,
  readSessionIdFromFile,
  clearSessionFile,
  getHeadFilePath,
  saveHeadSha,
  readHeadSha,
  clearHeadFile,
  getResumeThreadId,
  findThreadById,
  clearResumeSignal,
  loadJson,
  saveJson,
  saveMemoryMerged,
  appendAuditLine,
  getUser,
  detectTool,
  getSessionId,
  getBranch,
  parseJsonlFile,
  extractNarrativeFromEntries,
  extractNarrativeFromText,
  extractFailedFromEntries,
  extractFailedFromText,
  extractSessionFromAudit,
  migrateAuditAndPresence,
  // V2.5: injected-this-session tracking
  getInjectedPath,
  loadInjectedSet,
  saveInjectedSet,
  clearInjectedSet,
  isThreadInjected,
  markThreadInjected,
  // V2.5: active resumed thread
  getActiveResumeThreadId,
  setActiveResumeThreadId,
  clearActiveResumeThreadId,
  // V2.6: overlap warning tracking
  isOverlapWarned,
  markOverlapWarned,
  // V2.6.10: overlap signal file
  writeOverlapSignal,
  readAndDeleteOverlapSignal,
  isOverlapDismissed,
  markOverlapDismissed,
  // V2.5: cross-platform path helper
  normalizeSep,
  // V2.7: auto-sync
  syncStickyNote,
  // V2.9: Copilot CLI MCP config
  getCopilotCliMcpConfigPath,
  ensureMcpInCopilotCliConfig,
  // V2.10: rollback detection + backups
  detectLostThreads,
  loadLatestBackup,
  rotateBackup,
  acquireLock,
  releaseLock,
  // Cloud sync stubs (feature not yet implemented — on-stop.js uses these)
  useCloud: () => false,
  cloudReadThreads: async () => null,
  cloudWriteThread: async () => {},
  cloudAppendAudit: async () => {},
};
// tier1 test
