// Auto-generated by sticky-note environment provisioning
export default {
  name: "sticky-note-team",
  version: "1.0.0",
  description: "Team skills, agents, and commands provisioned by sticky-note",
};
